services:
  laravel_app:
    container_name: laravel_app
    environment:
      TZ: Asia/Tokyo
      ORDER_HISTORY_ENV: ${LARAVEL_ENV_FILE_DEFAULT}
    restart: always
    tty: true 
    networks:
      - laravel-nginx-network


  laravel_nginx:
    container_name: laravel_nginx
    environment:
      TZ: Asia/Tokyo
    restart: always
    tty: true
    depends_on:
      - laravel_app
    ports:
      - ${NGINX_PORT_MAPPING}:80
    networks:
      - laravel-nginx-network
  db:
    container_name: laravel-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password # 
      MYSQL_DATABASE: testdb
      MYSQL_USER: user_testdb
      MYSQL_PASSWORD: password
    #   # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - './docker/db/data:/var/lib/mysql'
    networks:
      - laravel-nginx-network
networks:
  laravel-nginx-network:
volumes:
  laravel_vendor:
